apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: pipelinewise-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PipelinewiseJob is the Schema for the pipelinewisejobs API
      displayName: Pipelinewise Job
      kind: PipelinewiseJob
      name: pipelinewisejobs.batch.pipelinewise
      version: v1alpha1
  description: Pipelinewise (https://transferwise.github.io/pipelinewise/) operator for Kubernetes
  displayName: pipelinewise-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ETL
  - Data Pipeline
  - Singer.io
  links:
  - name: Pipelinewise Operator
    url: https://pipelinewise-operator.domain
  maintainers:
  - email: dira.thea@gmail.com
    name: Aldira Putra Raharja
  maturity: alpha
  provider:
    name: Aldira Putra Raharja
    url: https://github.com/dirathea/pipelinewise-operator
  version: 0.0.0
