apiVersion: batch.pipelinewise/v1alpha1
kind: PipelinewiseJob
metadata:
  name: pipelinewisejob-sample-mysql-to-postgres
spec:
  # Schedule defines the cron expression
  schedule: "*/2 * * * *"
  # tap defines the source of the data. Since pipelinewise using singer.io, this fields describe the singer tap
  tap:
    mysql:
      db_conn:
        host: mariadb
        port: 3306
        user: root
        password: rKAVX4rQrQ
        dbname: test
      owner: dira.thea@gmail.com
      batch_size_rows: 20000
      stream_buffer_size: 0
      schemas:
        - source_schema: test
          target_schema: etl
          tables:
            - table_name: MOCK_DATA
              replication_method: FULL_TABLE
  # target defines the persistent target. Full example is on https://transferwise.github.io/pipelinewise/connectors/targets.html
  target:
    postgresql:
      host: postgresql
      port: 5432
      user: application-target
      password: application-secret-password
      dbname: destination
