// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTapConnectionSpec) DeepCopyInto(out *MySQLTapConnectionSpec) {
	*out = *in
	if in.SessionSQLs != nil {
		in, out := &in.SessionSQLs, &out.SessionSQLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTapConnectionSpec.
func (in *MySQLTapConnectionSpec) DeepCopy() *MySQLTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTapSchemaSpec) DeepCopyInto(out *MySQLTapSchemaSpec) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]MySQLTapTableSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTapSchemaSpec.
func (in *MySQLTapSchemaSpec) DeepCopy() *MySQLTapSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTapSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTapSpec) DeepCopyInto(out *MySQLTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]MySQLTapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTapSpec.
func (in *MySQLTapSpec) DeepCopy() *MySQLTapSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTapTableSpec) DeepCopyInto(out *MySQLTapTableSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTapTableSpec.
func (in *MySQLTapTableSpec) DeepCopy() *MySQLTapTableSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTapTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseGenericConfiguration) DeepCopyInto(out *PipelinewiseGenericConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseGenericConfiguration.
func (in *PipelinewiseGenericConfiguration) DeepCopy() *PipelinewiseGenericConfiguration {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseGenericConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJob) DeepCopyInto(out *PipelinewiseJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJob.
func (in *PipelinewiseJob) DeepCopy() *PipelinewiseJob {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinewiseJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJobList) DeepCopyInto(out *PipelinewiseJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelinewiseJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJobList.
func (in *PipelinewiseJobList) DeepCopy() *PipelinewiseJobList {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinewiseJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJobSpec) DeepCopyInto(out *PipelinewiseJobSpec) {
	*out = *in
	in.Tap.DeepCopyInto(&out.Tap)
	in.Target.DeepCopyInto(&out.Target)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJobSpec.
func (in *PipelinewiseJobSpec) DeepCopy() *PipelinewiseJobSpec {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJobStatus) DeepCopyInto(out *PipelinewiseJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJobStatus.
func (in *PipelinewiseJobStatus) DeepCopy() *PipelinewiseJobStatus {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLTargetSpec) DeepCopyInto(out *PostgreSQLTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLTargetSpec.
func (in *PostgreSQLTargetSpec) DeepCopy() *PostgreSQLTargetSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftTargetSpec) DeepCopyInto(out *RedshiftTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftTargetSpec.
func (in *RedshiftTargetSpec) DeepCopy() *RedshiftTargetSpec {
	if in == nil {
		return nil
	}
	out := new(RedshiftTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapSpec) DeepCopyInto(out *TapSpec) {
	*out = *in
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLTapSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapSpec.
func (in *TapSpec) DeepCopy() *TapSpec {
	if in == nil {
		return nil
	}
	out := new(TapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.Redshift != nil {
		in, out := &in.Redshift, &out.Redshift
		*out = new(RedshiftTargetSpec)
		**out = **in
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLTargetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}
