// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTapConnectionSpec) DeepCopyInto(out *GithubTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTapConnectionSpec.
func (in *GithubTapConnectionSpec) DeepCopy() *GithubTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(GithubTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTapSpec) DeepCopyInto(out *GithubTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTapSpec.
func (in *GithubTapSpec) DeepCopy() *GithubTapSpec {
	if in == nil {
		return nil
	}
	out := new(GithubTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleAnalyticsOauthCredentials) DeepCopyInto(out *GoogleAnalyticsOauthCredentials) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleAnalyticsOauthCredentials.
func (in *GoogleAnalyticsOauthCredentials) DeepCopy() *GoogleAnalyticsOauthCredentials {
	if in == nil {
		return nil
	}
	out := new(GoogleAnalyticsOauthCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleAnalyticsTapConnectionSpec) DeepCopyInto(out *GoogleAnalyticsTapConnectionSpec) {
	*out = *in
	if in.OauthCredentials != nil {
		in, out := &in.OauthCredentials, &out.OauthCredentials
		*out = new(GoogleAnalyticsOauthCredentials)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleAnalyticsTapConnectionSpec.
func (in *GoogleAnalyticsTapConnectionSpec) DeepCopy() *GoogleAnalyticsTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleAnalyticsTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleAnalyticsTapSpec) DeepCopyInto(out *GoogleAnalyticsTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleAnalyticsTapSpec.
func (in *GoogleAnalyticsTapSpec) DeepCopy() *GoogleAnalyticsTapSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleAnalyticsTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraTapConnectionSpec) DeepCopyInto(out *JiraTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraTapConnectionSpec.
func (in *JiraTapConnectionSpec) DeepCopy() *JiraTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(JiraTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraTapSpec) DeepCopyInto(out *JiraTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraTapSpec.
func (in *JiraTapSpec) DeepCopy() *JiraTapSpec {
	if in == nil {
		return nil
	}
	out := new(JiraTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTapConnectionSpec) DeepCopyInto(out *KafkaTapConnectionSpec) {
	*out = *in
	if in.PrimaryKeys != nil {
		in, out := &in.PrimaryKeys, &out.PrimaryKeys
		*out = new(KafkaTapPrimaryKey)
		**out = **in
	}
	if in.MaxRuntimeMs != nil {
		in, out := &in.MaxRuntimeMs, &out.MaxRuntimeMs
		*out = new(int)
		**out = **in
	}
	if in.ConsumerTimeoutMs != nil {
		in, out := &in.ConsumerTimeoutMs, &out.ConsumerTimeoutMs
		*out = new(int)
		**out = **in
	}
	if in.SessionTimeoutMs != nil {
		in, out := &in.SessionTimeoutMs, &out.SessionTimeoutMs
		*out = new(int)
		**out = **in
	}
	if in.HeartbeatIntervalMs != nil {
		in, out := &in.HeartbeatIntervalMs, &out.HeartbeatIntervalMs
		*out = new(int)
		**out = **in
	}
	if in.MaxPollIntervalMs != nil {
		in, out := &in.MaxPollIntervalMs, &out.MaxPollIntervalMs
		*out = new(int)
		**out = **in
	}
	if in.MaxPollRecords != nil {
		in, out := &in.MaxPollRecords, &out.MaxPollRecords
		*out = new(int)
		**out = **in
	}
	if in.CommitIntervalMs != nil {
		in, out := &in.CommitIntervalMs, &out.CommitIntervalMs
		*out = new(int)
		**out = **in
	}
	if in.LocalStoreBatchSizeRows != nil {
		in, out := &in.LocalStoreBatchSizeRows, &out.LocalStoreBatchSizeRows
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTapConnectionSpec.
func (in *KafkaTapConnectionSpec) DeepCopy() *KafkaTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTapPrimaryKey) DeepCopyInto(out *KafkaTapPrimaryKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTapPrimaryKey.
func (in *KafkaTapPrimaryKey) DeepCopy() *KafkaTapPrimaryKey {
	if in == nil {
		return nil
	}
	out := new(KafkaTapPrimaryKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaTapSpec) DeepCopyInto(out *KafkaTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTapSpec.
func (in *KafkaTapSpec) DeepCopy() *KafkaTapSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixpanelTapConnectionSpec) DeepCopyInto(out *MixpanelTapConnectionSpec) {
	*out = *in
	if in.ExportEvents != nil {
		in, out := &in.ExportEvents, &out.ExportEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixpanelTapConnectionSpec.
func (in *MixpanelTapConnectionSpec) DeepCopy() *MixpanelTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MixpanelTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixpanelTapSpec) DeepCopyInto(out *MixpanelTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixpanelTapSpec.
func (in *MixpanelTapSpec) DeepCopy() *MixpanelTapSpec {
	if in == nil {
		return nil
	}
	out := new(MixpanelTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBTapConnectionSpec) DeepCopyInto(out *MongoDBTapConnectionSpec) {
	*out = *in
	if in.WriteBatchRows != nil {
		in, out := &in.WriteBatchRows, &out.WriteBatchRows
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBTapConnectionSpec.
func (in *MongoDBTapConnectionSpec) DeepCopy() *MongoDBTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBTapSpec) DeepCopyInto(out *MongoDBTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBTapSpec.
func (in *MongoDBTapSpec) DeepCopy() *MongoDBTapSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTapConnectionSpec) DeepCopyInto(out *MySQLTapConnectionSpec) {
	*out = *in
	if in.SessionSQLs != nil {
		in, out := &in.SessionSQLs, &out.SessionSQLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTapConnectionSpec.
func (in *MySQLTapConnectionSpec) DeepCopy() *MySQLTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLTapSpec) DeepCopyInto(out *MySQLTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLTapSpec.
func (in *MySQLTapSpec) DeepCopy() *MySQLTapSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleTapConnectionSpec) DeepCopyInto(out *OracleTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleTapConnectionSpec.
func (in *OracleTapConnectionSpec) DeepCopy() *OracleTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(OracleTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleTapSpec) DeepCopyInto(out *OracleTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleTapSpec.
func (in *OracleTapSpec) DeepCopy() *OracleTapSpec {
	if in == nil {
		return nil
	}
	out := new(OracleTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJob) DeepCopyInto(out *PipelinewiseJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJob.
func (in *PipelinewiseJob) DeepCopy() *PipelinewiseJob {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinewiseJob) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJobList) DeepCopyInto(out *PipelinewiseJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelinewiseJob, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJobList.
func (in *PipelinewiseJobList) DeepCopy() *PipelinewiseJobList {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJobList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinewiseJobList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJobSpec) DeepCopyInto(out *PipelinewiseJobSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(bool)
		**out = **in
	}
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	in.Tap.DeepCopyInto(&out.Tap)
	in.Target.DeepCopyInto(&out.Target)
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJobSpec.
func (in *PipelinewiseJobSpec) DeepCopy() *PipelinewiseJobSpec {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJobSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinewiseJobStatus) DeepCopyInto(out *PipelinewiseJobStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinewiseJobStatus.
func (in *PipelinewiseJobStatus) DeepCopy() *PipelinewiseJobStatus {
	if in == nil {
		return nil
	}
	out := new(PipelinewiseJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLTapConnectionSpec) DeepCopyInto(out *PostgreSQLTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLTapConnectionSpec.
func (in *PostgreSQLTapConnectionSpec) DeepCopy() *PostgreSQLTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLTapSpec) DeepCopyInto(out *PostgreSQLTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLTapSpec.
func (in *PostgreSQLTapSpec) DeepCopy() *PostgreSQLTapSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLTargetSpec) DeepCopyInto(out *PostgreSQLTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLTargetSpec.
func (in *PostgreSQLTargetSpec) DeepCopy() *PostgreSQLTargetSpec {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftTargetSpec) DeepCopyInto(out *RedshiftTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftTargetSpec.
func (in *RedshiftTargetSpec) DeepCopy() *RedshiftTargetSpec {
	if in == nil {
		return nil
	}
	out := new(RedshiftTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CSVTableMappingSpec) DeepCopyInto(out *S3CSVTableMappingSpec) {
	*out = *in
	if in.KeyProperties != nil {
		in, out := &in.KeyProperties, &out.KeyProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CSVTableMappingSpec.
func (in *S3CSVTableMappingSpec) DeepCopy() *S3CSVTableMappingSpec {
	if in == nil {
		return nil
	}
	out := new(S3CSVTableMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CSVTapConnectionSpec) DeepCopyInto(out *S3CSVTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CSVTapConnectionSpec.
func (in *S3CSVTapConnectionSpec) DeepCopy() *S3CSVTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(S3CSVTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CSVTapSchemaSpec) DeepCopyInto(out *S3CSVTapSchemaSpec) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]S3CSVTapTableSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CSVTapSchemaSpec.
func (in *S3CSVTapSchemaSpec) DeepCopy() *S3CSVTapSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(S3CSVTapSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CSVTapSpec) DeepCopyInto(out *S3CSVTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]S3CSVTapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
	if in.BatchSizeRows != nil {
		in, out := &in.BatchSizeRows, &out.BatchSizeRows
		*out = new(int)
		**out = **in
	}
	if in.StreamBufferSize != nil {
		in, out := &in.StreamBufferSize, &out.StreamBufferSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CSVTapSpec.
func (in *S3CSVTapSpec) DeepCopy() *S3CSVTapSpec {
	if in == nil {
		return nil
	}
	out := new(S3CSVTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CSVTapTableSpec) DeepCopyInto(out *S3CSVTapTableSpec) {
	*out = *in
	in.Mapping.DeepCopyInto(&out.Mapping)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CSVTapTableSpec.
func (in *S3CSVTapTableSpec) DeepCopy() *S3CSVTapTableSpec {
	if in == nil {
		return nil
	}
	out := new(S3CSVTapTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3CSVTargetSpec) DeepCopyInto(out *S3CSVTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3CSVTargetSpec.
func (in *S3CSVTargetSpec) DeepCopy() *S3CSVTargetSpec {
	if in == nil {
		return nil
	}
	out := new(S3CSVTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceTapConnectionSpec) DeepCopyInto(out *SalesforceTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceTapConnectionSpec.
func (in *SalesforceTapConnectionSpec) DeepCopy() *SalesforceTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SalesforceTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SalesforceTapSpec) DeepCopyInto(out *SalesforceTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SalesforceTapSpec.
func (in *SalesforceTapSpec) DeepCopy() *SalesforceTapSpec {
	if in == nil {
		return nil
	}
	out := new(SalesforceTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSpec) DeepCopyInto(out *SecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSpec.
func (in *SecretSpec) DeepCopy() *SecretSpec {
	if in == nil {
		return nil
	}
	out := new(SecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShopifyTapConnectionSpec) DeepCopyInto(out *ShopifyTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShopifyTapConnectionSpec.
func (in *ShopifyTapConnectionSpec) DeepCopy() *ShopifyTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ShopifyTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShopifyTapSpec) DeepCopyInto(out *ShopifyTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShopifyTapSpec.
func (in *ShopifyTapSpec) DeepCopy() *ShopifyTapSpec {
	if in == nil {
		return nil
	}
	out := new(ShopifyTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackTapConnectionSpec) DeepCopyInto(out *SlackTapConnectionSpec) {
	*out = *in
	if in.Channels != nil {
		in, out := &in.Channels, &out.Channels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackTapConnectionSpec.
func (in *SlackTapConnectionSpec) DeepCopy() *SlackTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SlackTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackTapSpec) DeepCopyInto(out *SlackTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackTapSpec.
func (in *SlackTapSpec) DeepCopy() *SlackTapSpec {
	if in == nil {
		return nil
	}
	out := new(SlackTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeTapConnectionSpec) DeepCopyInto(out *SnowflakeTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeTapConnectionSpec.
func (in *SnowflakeTapConnectionSpec) DeepCopy() *SnowflakeTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(SnowflakeTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeTapSpec) DeepCopyInto(out *SnowflakeTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeTapSpec.
func (in *SnowflakeTapSpec) DeepCopy() *SnowflakeTapSpec {
	if in == nil {
		return nil
	}
	out := new(SnowflakeTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeTargetSpec) DeepCopyInto(out *SnowflakeTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeTargetSpec.
func (in *SnowflakeTargetSpec) DeepCopy() *SnowflakeTargetSpec {
	if in == nil {
		return nil
	}
	out := new(SnowflakeTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapSchemaSpec) DeepCopyInto(out *TapSchemaSpec) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]TapTableSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapSchemaSpec.
func (in *TapSchemaSpec) DeepCopy() *TapSchemaSpec {
	if in == nil {
		return nil
	}
	out := new(TapSchemaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapSpec) DeepCopyInto(out *TapSpec) {
	*out = *in
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Oracle != nil {
		in, out := &in.Oracle, &out.Oracle
		*out = new(OracleTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.S3CSV != nil {
		in, out := &in.S3CSV, &out.S3CSV
		*out = new(S3CSVTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Snowflake != nil {
		in, out := &in.Snowflake, &out.Snowflake
		*out = new(SnowflakeTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongoDB != nil {
		in, out := &in.MongoDB, &out.MongoDB
		*out = new(MongoDBTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Salesforce != nil {
		in, out := &in.Salesforce, &out.Salesforce
		*out = new(SalesforceTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Zendesk != nil {
		in, out := &in.Zendesk, &out.Zendesk
		*out = new(ZendeskTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Jira != nil {
		in, out := &in.Jira, &out.Jira
		*out = new(JiraTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Zuora != nil {
		in, out := &in.Zuora, &out.Zuora
		*out = new(ZuoraTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GoogleAnalytics != nil {
		in, out := &in.GoogleAnalytics, &out.GoogleAnalytics
		*out = new(GoogleAnalyticsTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Github != nil {
		in, out := &in.Github, &out.Github
		*out = new(GithubTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Shopify != nil {
		in, out := &in.Shopify, &out.Shopify
		*out = new(ShopifyTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Mixpanel != nil {
		in, out := &in.Mixpanel, &out.Mixpanel
		*out = new(MixpanelTapSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Twilio != nil {
		in, out := &in.Twilio, &out.Twilio
		*out = new(TwilioTapSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapSpec.
func (in *TapSpec) DeepCopy() *TapSpec {
	if in == nil {
		return nil
	}
	out := new(TapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapTableSpec) DeepCopyInto(out *TapTableSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapTableSpec.
func (in *TapTableSpec) DeepCopy() *TapTableSpec {
	if in == nil {
		return nil
	}
	out := new(TapTableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetSpec) DeepCopyInto(out *TargetSpec) {
	*out = *in
	if in.Redshift != nil {
		in, out := &in.Redshift, &out.Redshift
		*out = new(RedshiftTargetSpec)
		**out = **in
	}
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLTargetSpec)
		**out = **in
	}
	if in.Snowflake != nil {
		in, out := &in.Snowflake, &out.Snowflake
		*out = new(SnowflakeTargetSpec)
		**out = **in
	}
	if in.S3CSV != nil {
		in, out := &in.S3CSV, &out.S3CSV
		*out = new(S3CSVTargetSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetSpec.
func (in *TargetSpec) DeepCopy() *TargetSpec {
	if in == nil {
		return nil
	}
	out := new(TargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TwilioTapConnectionSpec) DeepCopyInto(out *TwilioTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TwilioTapConnectionSpec.
func (in *TwilioTapConnectionSpec) DeepCopy() *TwilioTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(TwilioTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TwilioTapSpec) DeepCopyInto(out *TwilioTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TwilioTapSpec.
func (in *TwilioTapSpec) DeepCopy() *TwilioTapSpec {
	if in == nil {
		return nil
	}
	out := new(TwilioTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZendeskTapConnectionSpec) DeepCopyInto(out *ZendeskTapConnectionSpec) {
	*out = *in
	if in.RateLimit != nil {
		in, out := &in.RateLimit, &out.RateLimit
		*out = new(int)
		**out = **in
	}
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZendeskTapConnectionSpec.
func (in *ZendeskTapConnectionSpec) DeepCopy() *ZendeskTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ZendeskTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZendeskTapSpec) DeepCopyInto(out *ZendeskTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZendeskTapSpec.
func (in *ZendeskTapSpec) DeepCopy() *ZendeskTapSpec {
	if in == nil {
		return nil
	}
	out := new(ZendeskTapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZuoraTapConnectionSpec) DeepCopyInto(out *ZuoraTapConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZuoraTapConnectionSpec.
func (in *ZuoraTapConnectionSpec) DeepCopy() *ZuoraTapConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ZuoraTapConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZuoraTapSpec) DeepCopyInto(out *ZuoraTapSpec) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]TapSchemaSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Connection = in.Connection
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZuoraTapSpec.
func (in *ZuoraTapSpec) DeepCopy() *ZuoraTapSpec {
	if in == nil {
		return nil
	}
	out := new(ZuoraTapSpec)
	in.DeepCopyInto(out)
	return out
}
