apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipelinewise-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipelinewise-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "pipelinewise-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
