# permissions for end users to edit pipelinewisejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelinewisejob-editor-role
rules:
- apiGroups:
  - batch.pipelinewise
  resources:
  - pipelinewisejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.pipelinewise
  resources:
  - pipelinewisejobs/status
  verbs:
  - get
