# permissions for end users to view pipelinewisejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pipelinewise-operator.fullname" . }}-viewer-role
rules:
- apiGroups:
  - batch.pipelinewise
  resources:
  - pipelinewisejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.pipelinewise
  resources:
  - pipelinewisejobs/status
  verbs:
  - get
