name: PR checker Test

on: pull_request

jobs:
  crd-build-and-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Generate and Test
        run: |
          make test
      - name: Test Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: dirathea/pipelinewise-operator:${{ github.sha }}